//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TrapRcvr.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TRAPRCVR_DIALOG             102
#define IDP_SOCKETS_INIT_FAILED         103
#define IDD_PROPPAGEACTIONS             106
#define IDR_MAINFRAME                   128
#define IDD_TRALERT                     129
#define IDD_DIALOGMONITOR               130
#define IDD_PROPPAGELOGGING             131
#define IDD_PROPPAGEMISC                132
#define IDD_PROPPAGEEXPLODERS           133
#define IDD_DIALOGACTIONADD             134
#define IDD_DIALOGEXPLODERADD           136
#define IDD_PROPPAGEEMAIL               137
#define IDD_DIALOGEMAILADD              138
#define IDD_TRAPRCVRDTL_DIALOG          139
#define IDD_DIALOG1                     140
#define IDD_TRAPRCVRDTLV2_DIALOG        141
#define IDD_PROPPAGETRAPDATA            142
#define IDD_DIALOGSPECIFYENVVARS        143
#define IDD_DIALOGSPECIFYCMDLINE        144
#define IDR_MENU1                       145
#define IDD_PROPPAGEMIBS                145
#define IDD_DIALOGSMTPAUTH              147
#define IDD_DIALOGLOADMIBFILE           148
#define IDD_DIALOG2                     149
#define IDD_DIALOG3                     150
#define IDD_DIALOG4                     151
#define IDD_DIALOGEMAILSELECTION        152
#define IDD_DIALOGSELECTDEBUG           153
#define IDD_DIALOGSOUNDPLAY             154
#define IDD_DIALOGEXPLODERSELECTION     155
#define IDD_DIALOG5                     157
#define IDC_LIST1                       1000
#define IDC_STATICTRAPCOUNT             1001
#define IDC_STATICSOURCE                1003
#define IDC_PROGRESS                    1004
#define IDC_BUTTONADD                   1008
#define IDC_BUTTONMODIFY                1009
#define IDC_BUTTONDELETE                1010
#define IDC_LIST                        1011
#define IDC_CHECKEXPLODE                1012
#define IDC_LIST3                       1012
#define IDC_CHECKEXECUTE                1013
#define IDC_CHECKEMAIL                  1014
#define IDC_CHECKPAGE                   1015
#define IDC_CHECKTWEET                  1015
#define IDC_COMBOWATCH                  1016
#define IDC_EDITVALUE                   1017
#define IDC_BUTTONEXECUTECONFIGURE      1019
#define IDC_EDITHOST                    1020
#define IDC_EDITPORT                    1021
#define IDC_RADIOLOGGINGON              1022
#define IDC_RADIOLOGGINGOFF             1023
#define IDC_SLIDERFLUSHINTERVAL         1024
#define IDC_EDIT1                       1025
#define IDC_BUTTONBROWSE                1026
#define IDC_RADIOAPPEND                 1027
#define IDC_EDITGENERICTYPE             1027
#define IDC_STATICNUMBEROFMINUTES       1030
#define IDC_EDITVBDATA                  1030
#define IDC_RADIOOVERWRITE              1031
#define IDC_EDITVBOID                   1031
#define IDC_EDITSMTPSERVER              1032
#define IDC_EDITSMTPPORT                1033
#define IDC_EDITFROM                    1034
#define IDC_EDITTO                      1035
#define IDC_EDITSUBJECT                 1036
#define IDC_EDITMESSAGE                 1037
#define IDC_STATICUNITS                 1038
#define IDC_EDITLOGFILESIZE             1039
#define IDC_EDITPINGTIMEOUT             1040
#define IDC_CHECKTRAY                   1041
#define IDC_CHECKREV                    1042
#define IDC_SPINPORT                    1043
#define IDC_SPINLOGFILESIZE             1044
#define IDC_SPINPINGTIMEOUT             1045
#define IDC_EDITPORTNUMBER              1046
#define IDC_SPINTRAPNUMBER              1047
#define IDC_EDITCOMMUNITY               1048
#define IDC_EDITTRAPTYPE                1049
#define IDC_EDITSPECIFICTYPE            1050
#define IDC_EDITTIMESTAMP               1051
#define IDC_EDITIPADDRESS               1052
#define IDC_EDITSENDEROID               1053
#define IDC_EDITTRAPNUMBER              1054
#define IDC_EDITARGUMENTS               1055
#define IDC_EDITPROGRAM                 1057
#define IDC_BUTTON1                     1058
#define IDC_EDITREQUESTID               1059
#define IDC_EDITERRORSTATUS             1060
#define IDC_EDITERRORINDEX              1061
#define IDC_CHECKADDTRAPDATA            1062
#define IDC_CHECKSETASENVIRONMENTVARIABLES 1063
#define IDC_CHECKPASSASCOMMANDLINEPARAMETERS 1064
#define IDC_BUTTONSPECIFYVARIABLES      1072
#define IDC_BUTTONSPECIFYPARAMETERS     1073
#define IDC_STATICMSG2                  1074
#define IDC_CHECKIPADDRESS              1075
#define IDC_CHECKGENERICTYPE            1076
#define IDC_CHECKSPECIFICTYPE           1077
#define IDC_CHECKCOMMUNITY              1078
#define IDC_CHECKSENDEROID              1079
#define IDC_CHECKVARBINDDATA            1080
#define IDC_CHECKVARBINDOID             1081
#define IDC_CHECKVBDATA                 1087
#define IDC_CHECKVBOID                  1088
#define IDC_EDITLOGFILEFORMAT           1097
#define IDC_CHECKINFORMS                1098
#define IDC_CHECKDISCARD                1099
#define IDC_CHECKTRANSLATEOIDS          1100
#define IDC_BUTTONIMPORTMIB             1102
#define IDC_LISTLOADEDMIBS              1103
#define IDC_CHECKAUTHREQUIRED           1104
#define IDC_BUTTONSETAUTH               1105
#define IDC_EDITPASSWORD                1106
#define IDC_EDITUSER                    1107
#define IDC_BUTTONPREV                  1108
#define IDC_BUTTONNEXT                  1109
#define IDC_BUTTONUNLOADMIB             1110
#define IDC_EDITMIBFILENAME             1112
#define IDC_LIST2                       1113
#define IDC_EDITTYPE                    1114
#define IDC_EDITSENDERSOID              1116
#define IDC_EDITTRAPTYPEREQUESTID       1117
#define IDC_EDITSPECIFICTYPEERRORSTATUS 1118
#define IDC_EDITTIMESTAMPERRORINDEX     1119
#define IDC_STATICCOUNTLABEL            1120
#define IDC_STATICSOURCELABEL           1121
#define IDC_BUTTONSHOWRAW               1122
#define IDC_BUTTONEMAILCONFIGURE        1123
#define IDC_BUTTONDEBUG                 1124
#define IDC_CHECKSMTP                   1125
#define IDC_CHECK2                      1126
#define IDC_CHECKACTIONS                1126
#define IDC_CHECKADDVARBINDS            1126
#define IDC_CHECK3                      1127
#define IDC_CHECK4                      1128
#define IDC_CHECKPLAYSOUND              1129
#define IDC_BUTTONSOUNDCONFIGURE        1130
#define IDC_RADIOONCE                   1131
#define IDC_RADIOLOOP                   1132
#define IDC_SLIDERDURATION              1133
#define IDC_EDITFILENAME                1134
#define IDC_STATICDURATIONLABEL         1135
#define IDC_BUTTONEXPLODECONFIGURE      1136
#define IDC_EDITNAME                    1137
#define IDC_BUTTONTWEETCONFIGURE        1138
#define IDC_CHECKSSLREQUIRED            1139
#define IDC_CHECKPARTOFGROUP            1140
#define IDC_SPIN1                       1141
#define IDC_SPINDEDUP                   1141
#define IDC_EDITDEDUPNUMBER             1142
#define IDC_CHECK1                      1143
#define IDC_CHECKDODEDUP                1143
#define IDC_CHECKREALIP                 1143
#define IDC_CHECKREALIP1                1143
#define IDC_CHECKREQUIRESDESKTOP        1143
#define IDC_CHECKREQUIREDESKTOP         1143
#define IDC_EDITREALIP                  1144
#define IDC_EDITREALIP1                 1145
#define IDC_EDIT2                       1146
#define IDC_EDITSEPARATORCHAR           1146
#define ID_CLEARGUI                     32772
#define ID_CLEARTHISTRAP                32773
#define IDM_EXPORTCONFIG                32775
#define IDM_IMPORTCONFIG                32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        158
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1147
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
